// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _example_HH_
#define _example_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "readmem.h"
#include "example_tb.h"

namespace ap_rtl {

struct example : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > in1_strm_V_dout;
    sc_in< sc_logic > in1_strm_V_empty_n;
    sc_out< sc_logic > in1_strm_V_read;
    sc_in< sc_lv<32> > in2_strm_V_dout;
    sc_in< sc_logic > in2_strm_V_empty_n;
    sc_out< sc_logic > in2_strm_V_read;
    sc_out< sc_lv<32> > out_strm_V_din;
    sc_in< sc_logic > out_strm_V_full_n;
    sc_out< sc_logic > out_strm_V_write;


    // Module declarations
    example(sc_module_name name);
    SC_HAS_PROCESS(example);

    ~example();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    example_tb* tb_U;
    readmem* grp_readmem_fu_126;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > in1_strm_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln65_fu_135_p2;
    sc_signal< sc_lv<4> > i_fu_141_p2;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_logic > tb_ce0;
    sc_signal< sc_lv<32> > tb_q0;
    sc_signal< sc_lv<4> > tb_address1;
    sc_signal< sc_logic > tb_ce1;
    sc_signal< sc_logic > tb_we1;
    sc_signal< sc_logic > grp_readmem_fu_126_ap_start;
    sc_signal< sc_logic > grp_readmem_fu_126_ap_done;
    sc_signal< sc_logic > grp_readmem_fu_126_ap_idle;
    sc_signal< sc_logic > grp_readmem_fu_126_ap_ready;
    sc_signal< sc_logic > grp_readmem_fu_126_in_strm_V_read;
    sc_signal< sc_lv<32> > grp_readmem_fu_126_out_strm_V_din;
    sc_signal< sc_logic > grp_readmem_fu_126_out_strm_V_write;
    sc_signal< sc_lv<4> > grp_readmem_fu_126_tb_address0;
    sc_signal< sc_logic > grp_readmem_fu_126_tb_ce0;
    sc_signal< sc_lv<4> > i_0_i_reg_115;
    sc_signal< sc_logic > grp_readmem_fu_126_ap_start_reg;
    sc_signal< bool > ap_block_state2_ignore_call0;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > zext_ln68_fu_147_p1;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state2();
    void thread_ap_block_state2_ignore_call0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_readmem_fu_126_ap_start();
    void thread_i_fu_141_p2();
    void thread_icmp_ln65_fu_135_p2();
    void thread_in1_strm_V_blk_n();
    void thread_in1_strm_V_read();
    void thread_in2_strm_V_read();
    void thread_out_strm_V_din();
    void thread_out_strm_V_write();
    void thread_tb_address1();
    void thread_tb_ce0();
    void thread_tb_ce1();
    void thread_tb_we1();
    void thread_zext_ln68_fu_147_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
