-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity example is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in1_strm_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in1_strm_V_empty_n : IN STD_LOGIC;
    in1_strm_V_read : OUT STD_LOGIC;
    in2_strm_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in2_strm_V_empty_n : IN STD_LOGIC;
    in2_strm_V_read : OUT STD_LOGIC;
    out_strm_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_strm_V_full_n : IN STD_LOGIC;
    out_strm_V_write : OUT STD_LOGIC );
end;


architecture behav of example is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "example,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=13.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.138000,HLS_SYN_LAT=35,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=476,HLS_SYN_LUT=1305,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in1_strm_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln69_reg_125 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_i_reg_87 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln69_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_114_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_129 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal tb_ce0 : STD_LOGIC;
    signal tb_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tb_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tb_ce1 : STD_LOGIC;
    signal tb_we1 : STD_LOGIC;
    signal tb_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_readmem_fu_99_in_strm_V_read : STD_LOGIC;
    signal grp_readmem_fu_99_out_strm_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_readmem_fu_99_out_strm_V_write : STD_LOGIC;
    signal grp_readmem_fu_99_tb_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_readmem_fu_99_tb_ce0 : STD_LOGIC;
    signal grp_readmem_fu_99_tb_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_readmem_fu_99_tb_we0 : STD_LOGIC;
    signal grp_readmem_fu_99_tb_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_readmem_fu_99_tb_ce1 : STD_LOGIC;
    signal grp_readmem_fu_99_tb_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_readmem_fu_99_tb_we1 : STD_LOGIC;
    signal grp_readmem_fu_99_ap_start : STD_LOGIC;
    signal grp_readmem_fu_99_ap_done : STD_LOGIC;
    signal grp_readmem_fu_99_ap_ready : STD_LOGIC;
    signal grp_readmem_fu_99_ap_idle : STD_LOGIC;
    signal grp_readmem_fu_99_ap_continue : STD_LOGIC;
    signal ap_phi_mux_i_0_i_phi_fu_91_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_readmem_fu_99_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_sync_grp_readmem_fu_99_ap_ready : STD_LOGIC;
    signal ap_sync_grp_readmem_fu_99_ap_done : STD_LOGIC;
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_readmem_fu_99_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_readmem_fu_99_ap_done : STD_LOGIC := '0';
    signal zext_ln73_fu_120_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component readmem IS
    port (
        in_strm_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        in_strm_V_empty_n : IN STD_LOGIC;
        in_strm_V_read : OUT STD_LOGIC;
        out_strm_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_strm_V_full_n : IN STD_LOGIC;
        out_strm_V_write : OUT STD_LOGIC;
        tb_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        tb_ce0 : OUT STD_LOGIC;
        tb_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tb_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        tb_we0 : OUT STD_LOGIC;
        tb_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        tb_ce1 : OUT STD_LOGIC;
        tb_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tb_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        tb_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component example_tb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    tb_U : component example_tb
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_readmem_fu_99_tb_address0,
        ce0 => tb_ce0,
        q0 => tb_q0,
        address1 => tb_address1,
        ce1 => tb_ce1,
        we1 => tb_we1,
        d1 => in1_strm_V_dout,
        q1 => tb_q1);

    grp_readmem_fu_99 : component readmem
    port map (
        in_strm_V_dout => in2_strm_V_dout,
        in_strm_V_empty_n => in2_strm_V_empty_n,
        in_strm_V_read => grp_readmem_fu_99_in_strm_V_read,
        out_strm_V_din => grp_readmem_fu_99_out_strm_V_din,
        out_strm_V_full_n => out_strm_V_full_n,
        out_strm_V_write => grp_readmem_fu_99_out_strm_V_write,
        tb_address0 => grp_readmem_fu_99_tb_address0,
        tb_ce0 => grp_readmem_fu_99_tb_ce0,
        tb_d0 => grp_readmem_fu_99_tb_d0,
        tb_q0 => tb_q0,
        tb_we0 => grp_readmem_fu_99_tb_we0,
        tb_address1 => grp_readmem_fu_99_tb_address1,
        tb_ce1 => grp_readmem_fu_99_tb_ce1,
        tb_d1 => grp_readmem_fu_99_tb_d1,
        tb_q1 => tb_q1,
        tb_we1 => grp_readmem_fu_99_tb_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_readmem_fu_99_ap_start,
        ap_done => grp_readmem_fu_99_ap_done,
        ap_ready => grp_readmem_fu_99_ap_ready,
        ap_idle => grp_readmem_fu_99_ap_idle,
        ap_continue => grp_readmem_fu_99_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_readmem_fu_99_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_readmem_fu_99_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
                    ap_sync_reg_grp_readmem_fu_99_ap_done <= ap_const_logic_0;
                elsif ((grp_readmem_fu_99_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_readmem_fu_99_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_readmem_fu_99_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_readmem_fu_99_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
                    ap_sync_reg_grp_readmem_fu_99_ap_ready <= ap_const_logic_0;
                elsif ((grp_readmem_fu_99_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_readmem_fu_99_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_readmem_fu_99_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_readmem_fu_99_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_sync_grp_readmem_fu_99_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                    grp_readmem_fu_99_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_readmem_fu_99_ap_ready = ap_const_logic_1)) then 
                    grp_readmem_fu_99_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_i_reg_87_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln69_reg_125 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_i_reg_87 <= i_reg_129;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_i_reg_87 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_reg_129 <= i_fu_114_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln69_reg_125 <= icmp_ln69_fu_108_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln69_fu_108_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln69_fu_108_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln69_fu_108_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(in1_strm_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln69_reg_125)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln69_reg_125 = ap_const_lv1_0) and (in1_strm_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in1_strm_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln69_reg_125)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln69_reg_125 = ap_const_lv1_0) and (in1_strm_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(in1_strm_V_empty_n, icmp_ln69_reg_125)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln69_reg_125 = ap_const_lv1_0) and (in1_strm_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(ap_sync_grp_readmem_fu_99_ap_ready, ap_sync_grp_readmem_fu_99_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((ap_sync_grp_readmem_fu_99_ap_ready and ap_sync_grp_readmem_fu_99_ap_done) = ap_const_logic_0);
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln69_fu_108_p2)
    begin
        if ((icmp_ln69_fu_108_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_0_i_phi_fu_91_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln69_reg_125, i_0_i_reg_87, i_reg_129)
    begin
        if (((icmp_ln69_reg_125 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_i_0_i_phi_fu_91_p4 <= i_reg_129;
        else 
            ap_phi_mux_i_0_i_phi_fu_91_p4 <= i_0_i_reg_87;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_readmem_fu_99_ap_done <= (grp_readmem_fu_99_ap_done or ap_sync_reg_grp_readmem_fu_99_ap_done);
    ap_sync_grp_readmem_fu_99_ap_ready <= (grp_readmem_fu_99_ap_ready or ap_sync_reg_grp_readmem_fu_99_ap_ready);

    grp_readmem_fu_99_ap_continue_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
            grp_readmem_fu_99_ap_continue <= ap_const_logic_1;
        else 
            grp_readmem_fu_99_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_readmem_fu_99_ap_start <= grp_readmem_fu_99_ap_start_reg;
    i_fu_114_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_0_i_phi_fu_91_p4) + unsigned(ap_const_lv4_1));
    icmp_ln69_fu_108_p2 <= "1" when (ap_phi_mux_i_0_i_phi_fu_91_p4 = ap_const_lv4_A) else "0";

    in1_strm_V_blk_n_assign_proc : process(in1_strm_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln69_reg_125)
    begin
        if (((icmp_ln69_reg_125 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in1_strm_V_blk_n <= in1_strm_V_empty_n;
        else 
            in1_strm_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in1_strm_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln69_reg_125, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln69_reg_125 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in1_strm_V_read <= ap_const_logic_1;
        else 
            in1_strm_V_read <= ap_const_logic_0;
        end if; 
    end process;


    in2_strm_V_read_assign_proc : process(grp_readmem_fu_99_in_strm_V_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in2_strm_V_read <= grp_readmem_fu_99_in_strm_V_read;
        else 
            in2_strm_V_read <= ap_const_logic_0;
        end if; 
    end process;

    out_strm_V_din <= grp_readmem_fu_99_out_strm_V_din;

    out_strm_V_write_assign_proc : process(grp_readmem_fu_99_out_strm_V_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_strm_V_write <= grp_readmem_fu_99_out_strm_V_write;
        else 
            out_strm_V_write <= ap_const_logic_0;
        end if; 
    end process;


    tb_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, grp_readmem_fu_99_tb_address1, ap_CS_fsm_state5, zext_ln73_fu_120_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tb_address1 <= zext_ln73_fu_120_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tb_address1 <= grp_readmem_fu_99_tb_address1;
        else 
            tb_address1 <= "XXXX";
        end if; 
    end process;


    tb_ce0_assign_proc : process(grp_readmem_fu_99_tb_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tb_ce0 <= grp_readmem_fu_99_tb_ce0;
        else 
            tb_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tb_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, grp_readmem_fu_99_tb_ce1, ap_CS_fsm_state5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tb_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tb_ce1 <= grp_readmem_fu_99_tb_ce1;
        else 
            tb_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    tb_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln69_reg_125, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln69_reg_125 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tb_we1 <= ap_const_logic_1;
        else 
            tb_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln73_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i_reg_87),64));
end behav;
